name: allure-report
 
on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
#  schedule:
#      - cron: '0 1 * * *'

jobs:

  build:

    name: Test on Ubuntu

    runs-on: [ubuntu-latest]

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Native Selenium Grid
        run: docker-compose up -d
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Check running containers
        run: docker ps
      - name: Run all tests
        continue-on-error: true
        run: mvn test
